# Generated by Django 5.2.6 on 2025-09-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='format',
            field=models.CharField(choices=[('STD', 'Standard'), ('MOD', 'Modern'), ('LGC', 'Legacy'), ('VIN', 'Vintage'), ('EDH', 'Commander'), ('PPR', 'Pauper'), ('NON', 'No Format')], default='NON', max_length=3),
        ),
    ]
