# Generated by Django 5.2.6 on 2025-09-25 02:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deck_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='scryfall_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deck',
            name='format',
            field=models.CharField(choices=[('STD', 'Standard'), ('MOD', 'Modern'), ('LGC', 'Legacy'), ('VIN', 'Vintage'), ('EDH', 'Commander'), ('PPR', 'Pauper'), ('NON', 'Sem Formato')], default='NON', max_length=3),
        ),
    ]
